version: '3.8'

networks:
  default:
    name: confluent-net
    external: true

services:
  akhq:
    image: tchiotludo/akhq:dev
    hostname: akhq
    container_name: akhq
    ports:
      - 8080:8080
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "broker1:29092, broker2:29093, broker3:29094"
    restart: 'no'
