version: '3.8'

networks:
  default:
    name: confluent-net
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    env_file:
      - envs/zookeeper.env
    restart: 'no'