# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3.8'

networks:
  default:
    name: confluent-net
    external: true

services:
  jobmanager:
    image: docker.io/bitnami/flink:1
    ports:
      - 6123:6123
      - 8081:8081
    environment:
      - FLINK_MODE=jobmanager
      - FLINK_CFG_REST_BIND__ADDRESS=0.0.0.0

  taskmanager:
    image: docker.io/bitnami/flink:1
    ports:
      - 6121:6121
      - 6122:6122
    environment:
      - FLINK_MODE=taskmanager
      - FLINK_JOB_MANAGER_RPC_ADDRESS=jobmanager